[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish (relative to the repository root)
  publish = "dist"
  
  # Base directory for the build (this is important since we're in the frontend folder)
  base = "frontend"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # NPM version (optional)
  NPM_VERSION = "9"

# Redirect rules for Single Page Application (SPA)
# This ensures that all routes are handled by React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache control for HTML files (don't cache)
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    # Cache static assets for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    # Cache CSS files for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    # Cache JS files for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

# Environment-specific settings
[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"

# Functions directory (if you plan to add serverless functions later)
[build]
  functions = "netlify/functions"
