[build]
  # Build command with clean install to ensure Rollup dependency is properly installed
  command = "rm -rf node_modules package-lock.json && npm install && npm run build"

  # Directory to publish (relative to the repository root)
  publish = "dist"

  # Base directory for the build (this is important since we're in the frontend folder)
  base = "frontend"

  # Functions directory for serverless functions
  functions = "netlify/functions"

[build.environment]
  # Node.js version
  NODE_VERSION = "22"

  # NPM version (optional)
  NPM_VERSION = "10"

# Redirect rules for Single Page Application
# Since we're now using a one-page design, we only need basic redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache control for HTML files (don't cache)
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    # Cache static assets for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    # Cache CSS files for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    # Cache JS files for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

# Environment-specific settings
[context.production]
  command = "rm -rf node_modules package-lock.json && npm install && npm run build"

[context.deploy-preview]
  command = "rm -rf node_modules package-lock.json && npm install && npm run build"

[context.branch-deploy]
  command = "rm -rf node_modules package-lock.json && npm install && npm run build"


